# Generated by Django 5.1.3 on 2025-02-14 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terminology', '0002_alter_element_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='element',
            unique_together={('version', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together={('refbook', 'version')},
        ),
    ]
