# Generated by Django 5.1.3 on 2025-02-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminology', '0003_alter_element_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='element',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='version',
            constraint=models.UniqueConstraint(fields=('refbook', 'version'), name='unique_refbook_version'),
        ),
    ]
