# Generated by Django 5.1.3 on 2025-02-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminology', '0005_remove_version_unique_refbook_version_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'verbose_name': 'Версия справочника', 'verbose_name_plural': 'Версии справочников'},
        ),
        migrations.AlterUniqueTogether(
            name='element',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='version',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='version',
            constraint=models.UniqueConstraint(fields=('refbook', 'version'), name='unique_version_per_refbook'),
        ),
    ]
